///|
/// Command helpers.

///|
/// Title of the command, like `save`.

///|
/// Title of the command, like `save`.

///|
/// The identifier of the actual command handler.
/// @see {@link commands.registerCommand}

///|
/// The identifier of the actual command handler.
/// @see {@link commands.registerCommand}

///|
/// A tooltip for the command, when represented in the UI.

///|
/// A tooltip for the command, when represented in the UI.

///|
/// A tooltip for the command, when represented in the UI.

///|
/// Arguments that the command handler should be
/// invoked with.

///|
/// Arguments that the command handler should be
/// invoked with.

///|
/// Arguments that the command handler should be
/// invoked with.
