///|
pub type QuickDiffProviderObject

///|
pub type AuthenticationProviderObject

///|
pub type TreeDataProviderObject[T]

///|
pub type WebviewViewProviderObject

///|
pub type CustomTextEditorProviderObject

///|
pub type CustomReadonlyEditorProviderObject

///|
pub type CustomEditorProviderObject

///|
pub type TerminalLinkProviderObject

///|
pub type TerminalProfileProviderObject

///|
pub type FileDecorationProviderObject

///|
pub type CommentingRangeProviderObject

///|
pub type TaskProviderObject

///|
pub type TextDocumentContentProviderObject

///|
pub type HoverProviderObject

///|
pub type SignatureHelpProviderObject

///|
pub type CompletionItemProviderObject[T]

///|
pub type DefinitionProviderObject

///|
pub type ImplementationProviderObject

///|
pub type TypeDefinitionProviderObject

///|
pub type DeclarationProviderObject

///|
pub type DocumentHighlightProviderObject

///|
pub type CodeActionProviderObject[T]

///|
pub type DocumentFormattingEditProviderObject

///|
pub type DocumentRangeFormattingEditProviderObject

///|
pub type OnTypeFormattingEditProviderObject

///|
pub type DocumentLinkProviderObject[T]

///|
pub type CodeLensProviderObject[T]

///|
pub type DocumentColorProviderObject

///|
pub type FoldingRangeProviderObject

///|
pub type DocumentSymbolProviderObject

///|
pub type WorkspaceSymbolProviderObject[T]

///|
pub type CallHierarchyProviderObject

///|
pub type TypeHierarchyProviderObject

///|
pub type InlayHintsProviderObject[T]

///|
pub type DocumentSemanticTokensProviderObject

///|
pub type DocumentRangeSemanticTokensProviderObject

///|
pub type InlineCompletionItemProviderObject

///|
pub type InlineValuesProviderObject

///|
pub type DocumentDropEditProviderObject

///|
pub type DocumentPasteEditProviderObject

///|
pub type ReferenceProviderObject

///|
pub type RenameProviderObject

///|
pub type SelectionRangeProviderObject

///|
pub type LinkedEditingRangeProviderObject
